Select chains to benchmark in the benchmarking CI (#677)
* support multi chains to benchmark

* correct these code according to  kai's advice

diff --git a/.github/workflows/benchmark-runtime-weights.yml b/.github/workflows/benchmark-runtime-weights.yml
--- a/.github/workflows/benchmark-runtime-weights.yml
+++ b/.github/workflows/benchmark-runtime-weights.yml
@@ -3,14 +3,21 @@ name: Benchmark runtime weights
 on:
   workflow_dispatch:
     inputs:
-      chain:
-        type: choice
-        description: The chain whose runtime is benchmarked, all = rococo+litmus+litentry
-        options:
-          - all
-          - litmus
-          - litentry
-          - rococo
+      litentry:
+        type: boolean
+        description: The litentry will be benchmarked
+        required: true
+        default: true
+      litmus:
+        type: boolean
+        description: The litmus will be benchmarked
+        required: true
+        default: true
+      rococo:
+        type: boolean
+        description: The rococo will be benchmarked
+        required: true
+        default: true
       pallets:
         description: pallets to benchmark, * for all, or comma listed (e.g. frame-system,pallet-proxy)
         default: "*"
@@ -24,6 +31,24 @@ jobs:
   build-and-benchmark:
     runs-on: self-hosted
     steps:
+      - name: Set env
+        run: |
+          chain=""
+          if [ "${{ github.event.inputs.litmus }}" = "true" ]; then
+            chain="$chain litmus"
+          fi
+          if [ "${{ github.event.inputs.litentry }}" = "true" ]; then
+            chain="$chain litentry"
+          fi
+          if [ "${{ github.event.inputs.rococo }}" = "true" ]; then
+            chain="$chain rococo"
+          fi
+          if [ "$chain" = "" ]; then
+            echo "::error::Please select at least one chain."
+            exit 1
+          fi
+          echo "CHAIN=$chain" >> $GITHUB_ENV
+
       - name: Checkout codes on ${{ github.ref }}
         uses: actions/checkout@v3
         with:
@@ -42,17 +67,14 @@ jobs:
           [ -z "$(docker images --filter=dangling=true -q)" ] || docker rmi -f $(docker images --filter=dangling=true -q)
 
       # exit status should propagate through ssh
-      - name: Remotely benchmark pallets ${{ github.event.inputs.pallets }} for ${{ github.event.inputs.chain }}
+      - name: Remotely benchmark pallets ${{ github.event.inputs.pallets }} for ${{ env.CHAIN }}
         timeout-minutes: 240
         run: |
           # prepend the asterisk with \ to go through ssh
           arg="${{ github.event.inputs.pallets }}"
-          chain="${{ github.event.inputs.chain }}"
+          chain="${{ env.CHAIN }}"
           if [ "$arg" = "*" ]; then
             arg="\\$arg";
-          fi
-          if [ "$chain" = "all" ]; then
-            chain="rococo litmus litentry"
           fi
           for c in $chain; do
             ssh -x "${{ env.REMOTE_HOST }}" 'bash -s' < scripts/benchmark-weight-remote.sh "$c" "${GITHUB_REF#refs/heads/}" "$arg"
@@ -77,7 +99,7 @@ jobs:
             It updates the weights files under `runtime/*/src/weights/*.rs` after running benchmarks on the remote machine: ${{ env.REMOTE_HOST }}
 
             Pallets: "${{ github.event.inputs.pallets }}"
-            Chain: "${{ github.event.inputs.chain }}" [all = rococo,litmus,litentry]
+            Chain: "${{ env.CHAIN }}"
             Github action run: https://github.com/litentry/litentry-parachain/actions/runs/${{ github.run_id }}
           labels: |
             S1-pleasereview
