Test github action context

diff --git a/.github/workflows/build_and_run_test.yml b/.github/workflows/build_and_run_test.yml
--- a/.github/workflows/build_and_run_test.yml
+++ b/.github/workflows/build_and_run_test.yml
@@ -18,25 +18,35 @@ jobs:
     - uses: actions/checkout@v2
       with:
         submodules: true
-    - name: Add wasm toolchain
-      uses: actions-rs/toolchain@v1
-      with:
-        toolchain: nightly-2021-03-24
-        target: wasm32-unknown-unknown
-        override: true
-    - name: Build relay node and parachain
-      run: |
-        cargo build --release
-        cd polkadot
-        cargo build --release
-        cd ..
-    - name: Build token server
-      run: |
-        cd token-server
-        cargo build --release
-        cd ..
+    # - name: Add wasm toolchain
+    #   uses: actions-rs/toolchain@v1
+    #   with:
+    #     toolchain: nightly-2021-03-24
+    #     target: wasm32-unknown-unknown
+    #     override: true
+    # - name: Build relay node and parachain
+    #   run: |
+    #     cargo build --release
+    #     cd polkadot
+    #     cargo build --release
+    #     cd ..
+    # - name: Build token server
+    #   run: |
+    #     cd token-server
+    #     cargo build --release
+    #     cd ..
     - name: Run integration test
       run: |
-        cd ts-tests
-        ./scripts/run-test.sh
+        exit 1
+        # cd ts-tests
+        # ./scripts/run-test.sh
       shell: bash {0}
+    - name: Clean up
+      if: ${{ failure() }}
+      run: |
+        echo "Failed"
+
+    - name: Clean up
+      if: ${{ success() }}
+      run: |
+        echo "Success"
