test docker

diff --git a/.github/workflows/release-ts-api-package.yml b/.github/workflows/release-ts-api-package.yml
--- a/.github/workflows/release-ts-api-package.yml
+++ b/.github/workflows/release-ts-api-package.yml
@@ -13,7 +13,7 @@ on:
           required: true
           default: 'latest'
         release-tag:
-          description: 'Ts api release tag'
+          description: 'Client-api release tag'
           required: true
           default: 'latest'
 env:
@@ -55,37 +55,37 @@ jobs:
           cd tee-worker/docker
           docker compose -f docker-compose.yml -f lit-ts-api-package-build.yml up --no-build --exit-code-from lit-ts-api-package-build lit-ts-api-package-build
 
-      - name: Use Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: 18
-          registry-url: https://npm.pkg.github.com/
+      # - name: Use Node.js
+      #   uses: actions/setup-node@v3
+      #   with:
+      #     node-version: 18
+      #     registry-url: https://npm.pkg.github.com/
 
-      - name: Setup npm config
-        run: |
-          echo "//npm.pkg.github.com/:_authToken=\${{ secrets.RELEASE_TS_API_PACKAGE_TOKEN }}" > .npmrc
-          npm config set @litentry:registry https://npm.pkg.github.com
+      # - name: Setup npm config
+      #   run: |
+      #     echo "//npm.pkg.github.com/:_authToken=\${{ secrets.RELEASE_TS_API_PACKAGE_TOKEN }}" > .npmrc
+      #     npm config set @litentry:registry https://npm.pkg.github.com
 
-      - name: Publish parachain API and sidechain API
-        working-directory: ./tee-worker/client-api
-        run: |
-          apis=("parachain-api" "sidechain-api")
-          for api in "${apis[@]}"; do
-            cd "$api"
+      # - name: Publish parachain API and sidechain API
+      #   working-directory: ./tee-worker/client-api
+      #   run: |
+      #     apis=("parachain-api" "sidechain-api")
+      #     for api in "${apis[@]}"; do
+      #       cd "$api"
 
-            # Check if dist and build files exist
-            if [ -d "dist" ] && [ -d "build" ]; then
-              echo "$api dist and build files exist."
-            else
-              echo "$api dist and build files do not exist. Publishing failed."
-              exit 1
-            fi
+      #       # Check if dist and build files exist
+      #       if [ -d "dist" ] && [ -d "build" ]; then
+      #         echo "$api dist and build files exist."
+      #       else
+      #         echo "$api dist and build files do not exist. Publishing failed."
+      #         exit 1
+      #       fi
 
-            npm publish --tag ${{ inputs.release-tag }}
+      #       npm publish --tag ${{ inputs.release-tag }}
 
-            echo "------------------------$api published------------------------"
-            cd ..
-          done
+      #       echo "------------------------$api published------------------------"
+      #       cd ..
+      #     done
 
       - name: Stop docker containers
         run: |
