fix comment

diff --git a/.github/workflows/release-ts-api-package.yml b/.github/workflows/release-ts-api-package.yml
--- a/.github/workflows/release-ts-api-package.yml
+++ b/.github/workflows/release-ts-api-package.yml
@@ -8,105 +8,20 @@ env:
   NODE_AUTH_TOKEN: ${{ secrets.RELEASE_TS_API_PACKAGE_TOKEN }}
 
 jobs:
-  parachain-build-dev:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Free up disk space
-        if: startsWith(runner.name, 'GitHub Actions')
-        uses: jlumbroso/free-disk-space@main
-        with:
-          tool-cache: true
-          swap-storage: false
-          large-packages: false
-
-      - uses: actions/checkout@v4
-        
-      - name: Pull docker image optinally
-        run: |
-          docker pull litentry/litentry-parachain:latest
-
-      - name: Save docker image
-        run: |
-          docker save litentry/litentry-parachain:latest | gzip > litentry-parachain-dev.tar.gz
-
-      - name: Upload docker image
-        uses: actions/upload-artifact@v3
-        with:
-          name: litentry-parachain-dev
-          path: litentry-parachain-dev.tar.gz
-          if-no-files-found: error
-
-      - name: Fail early
-        if: failure()
-        uses: andymckay/cancel-action@0.3
-
-  tee-build:
-    runs-on: ubuntu-latest
-    needs:
-      - parachain-build-dev
-    steps:
-      - name: Free up disk space
-        if: startsWith(runner.name, 'GitHub Actions')
-        uses: jlumbroso/free-disk-space@main
-        with:
-          tool-cache: true
-          swap-storage: false
-          large-packages: false
-
-      - uses: actions/checkout@v4
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-        with:
-
-          driver: docker
-
-      - name: Pull and tag worker and cli image optionally
-        run: |
-          docker pull litentry/litentry-worker:latest
-          docker pull litentry/litentry-cli:latest
-
-      - run: docker images --all
-
-      - name: Save docker images
-        run: docker save litentry/litentry-worker:latest litentry/litentry-cli:latest | gzip > litentry-tee.tar.gz
-
-      - name: Upload docker images
-        uses: actions/upload-artifact@v3
-        with:
-          name: litentry-tee
-          path: litentry-tee.tar.gz
-          if-no-files-found: error
-
-      - name: Fail early
-        if: failure()
-        uses: andymckay/cancel-action@0.3 
         
   update-publish:
     runs-on: ubuntu-latest
-    needs:
-      - parachain-build-dev
-      - tee-build
     steps:
       - uses: actions/checkout@v4
 
-      - name: Pull polkadot image
+      - name: Pull litentry image optionally
         run: |
           docker pull parity/polkadot
+          docker pull litentry/litentry-worker:latest
+          docker pull litentry/litentry-cli:latest
+          docker pull litentry/litentry-parachain:latest
 
-      - uses: actions/download-artifact@v3
-        with:
-          name: litentry-parachain-dev
-
-      - uses: actions/download-artifact@v3
-        with:
-          name: litentry-tee
-
-      - name: Load docker image
-        run: |
-          docker load < litentry-parachain-dev.tar.gz
-          docker load < litentry-tee.tar.gz
-          docker images
+      - run: docker images --all
 
       - name: Enable corepack and pnpm
         run: corepack enable && corepack enable pnpm
@@ -144,11 +59,29 @@ jobs:
         if: github.ref_name == 'dev' || github.ref_name == 'staging'
         run: |
           cd tee-worker/client-api/parachain-api
+
+          # Check if dist and build files exist
+          if [ -d "dist" ] && [ -d "build" ]; then
+            echo "Parachain API dist and build files exist."
+          else
+            echo "Parachain API dist and build files do not exist. Publishing failed."
+            exit 1
+          fi
+
           npm publish --tag ${{ github.ref_name }}
 
           echo "------------------------parachain API published------------------------"
 
           cd ../sidechain-api
+
+          # Check if dist and build files exist
+          if [ -d "dist" ] && [ -d "build" ]; then
+            echo "Parachain API dist and build files exist."
+          else
+            echo "Parachain API dist and build files do not exist. Publishing failed."
+            exit 1
+          fi
+
           npm publish --tag ${{ github.ref_name }}
 
           echo "------------------------sidechain API published------------------------"
